### ISSUE TITLE
Breaking - Don't use && and ||

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/if-env#4]
Example:

```
if-env NODE_ENV=production && npm run webpack:prod || npm run webpack:dev
```

If `webpack:prod` fails, then `webpack:dev` runs.  This isn't the desired behavior, as `if-env` only helps when everything _works_.

**Comment by mcchrish** [comment]
Is there a correct way for it?

**Comment by ericclemmons** [comment]
This is what I've switched to using:
> https://github.com/ericclemmons/per-env

**Much better**.  I'll probably deprecate this project in favor of that.

**Comment by felixfbecker** [comment]
Why not pass the commands to execute as a string?
```json
"test": "if-env COVERAGE then 'npm run coveralls' else 'npm run jshint && npm run test-unit && npm run test-integration"
```
Then just spawn the command with `childProcess.exec()`.
