### ISSUE TITLE
if-env NODE_ENV=production && npm run start:prod || npm start:dev

### ISSUE THREAD

**Issue by yavorskiy** [ericclemmons/if-env#6]
This command may play really bad joke with you, I learned it a hard way
```bash
if-env NODE_ENV=production && npm run start:prod || npm start:dev
```

if your app dies on unhandled exception then `npm run start:prod` returns no-zero code, then this expression proceeds to the `npm start:dev` and restarts your app in dev mode

**Comment by ericclemmons** [comment]
I had the same thing happen too :(

Our company has switched to `per-env` to avoid a lot of the `&& ||` bullcrap...
> https://github.com/ericclemmons/per-env/

**Comment by kentcdodds** [comment]
Perhaps the README should be updated to reveal this issue?

**Comment by kentcdodds** [comment]
Correction. The README was updated, but a new version hasn't been published since so the README on npm doesn't show the update.

**Comment by ericclemmons** [comment]
Oh, thanks for letting me know!  I'll push a new version.  Because of bash-level fun like this, I've mostly switched to using `per-env`:
> https://github.com/ericclemmons/per-env

Between `p-s` and `per-env`, looks like `package.json` could use some help ;)

**Comment by ericclemmons** [comment]
Promise I'm going to re-release.  Been busy with https://twitter.com/ericclemmons/status/951552612754698245

**Comment by ericclemmons** [comment]
Ok, `v1.0.4` is on NPM with what I assume to be the latest README.

It seems every project I've ever had deploys & publishes differently, so here's hoping it worked. :shrug:
